config/routes.rb
Rails.application.routes.draw do
  get 'posts', to: 'posts#index'
  get 'about', to: 'about#index'

  root 'home#index'

  get '/users/:id', to: 'users#profile', as: 'users_profile'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/continent.rb
class Continent < ApplicationRecord
    has_many :countries
end
class Continent < ApplicationRecord
    has_many :countries

    validates :name, presence: true
end

app/models/country.rb
class Country < ApplicationRecord
    belongs_to :continent

    validates :name, presence: true
end

app/models/gender.rb
class Gender < ApplicationRecord
    has_one :users, foreign_key: 'genders_id'

    validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :users, foreign_key: 'user_id'

    validates :creator, presence: true, length: { maximum: 500 }
    validates :title, presence: true, length: { maximum: 50 }
    validates :content, presence: true
    validates :tag, presence: true, length: { maximum: 50 }
    validates :user_id, presence: true
end

app/models/title.rb
class Title < ApplicationRecord
    has_many :user_titles
    has_many :users, through: :user_titles
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :gender, foreign_key: 'genders_id'
    belongs_to :country
    has_many :posts
    has_many :user_titles
    has_many :titles, through: :user_titles

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :bio, length: { maximum: 1000 }
    validates :genders_id, presence: true
    validates :country_id, presence: true
end

app/models/user_title.rb
class UserTitle < ApplicationRecord
    belongs_to :user
    belongs_to :title
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def show
    @title = Title.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = User.find(params[:id])
    @gender_name = Gender.find(@user.genders_id).name
    @country_name = Country.find(@user.country_id).name
  end

  def index
    @filtered_users = filter_users(params[:search]).page(params[:page]).per(20)
  end

  def filter_users(search_term)
    if search_term.present?
      User.where("name LIKE ?", "%#{search_term}%")
    else
      User.all
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/index.html.erb
<div class="container mb-5">
  <div class="row">
    <div class="col-md-10">
      <h2>About</h2>
      <p>This project is a member only site where users post about life updates. This project will not feature any CRUD function as this project doesn’t require it. It will only feature all the users and their profile for now.</p>
    </div>
  </div>
  <div class="row mt-2">
    <div class="col-md-8">
      <h2>Technologies</h2>
      <ul>
        <li>Ruby on Rails</li>
        <li>Bootstrap</li>
        <li>Faker</li>
      </ul>
      <img src="https://download.logo.wine/logo/Ruby_on_Rails/Ruby_on_Rails-Logo.wine.png" alt="Profile" class="img-thumbnail" style="max-width: 200px;">
      <p class="mt-4">User data is generated by using Faker, RandomAPI, and CSV Files by utilizing seeds and rake files</p>
      <h2>ERD</h2>
      <%= image_tag('IntroToRailsERD.png', alt: 'Rails ERD', style: "width: 75%;") %>
    </div>
    <div class="col-md-4">
      <div class="col-md-4 mt-2">
        <div class="d-flex flex-column align-items-center">
          <img src="https://media.licdn.com/dms/image/D5603AQEXNqtElPCefg/profile-displayphoto-shrink_800_800/0/1683570603430?e=1703721600&v=beta&t=E9RsqHx8RnGKJQDnQ2Jb1P7mR1SmDQ1qrAgZ7LhzTPs" alt="Profile" class="img-thumbnail" style="max-width: 150px;">
          <a href="https://www.linkedin.com/in/jonathan-jimena-jr-269124224/">Linkedin</a>
          <div>
            <h2>Contact</h2>
            <ul>
              <li>Jojo Jimena</li>
              <li>jjimena2@academic.rrc.ca</li>
            </ul>
            <h2>About Me</h2>
            <p>Hello, my name is Jojo Jimena and I've created this site for my term 5 elective, Full Stack. This is my first Ruby on Rails Project, and I'm enjoying it so far.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container" style="margin-top: -75px;">
  <div class="d-flex flex-column align-items-center justify-content-center vh-100">
    <h1>
      Intro to Rails Project
    </h1>
    <form class="d-flex w-100" role="search" method="get" action="<%= users_path %>">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroToRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="/users">Members</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="/posts">Create Post</a>
            </li>
          </ul>
          <% unless request.path == root_path %>
            <form class="d-flex" role="search" method="get" action="<%= users_path %>">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          <% end %>
        </div>
      </div>
    </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <div class="mt-5 pt-2">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<div class="container">
  <h1>Members</h1>
  <div class="row">
    <% @filtered_users.each do |data| %>
      <div class="col-md-3">
        <div class="card mb-4">
          <div class="card-body">
            <h6 class="card-title"><%= data.name %></h6>
            <%= link_to user_path(data) do %>
              <%= image_tag data.image, alt: data.name, class: "card-img-top" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
  <div class="pagination justify-content-center mb-5">
    <%= paginate @filtered_users %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container d-flex justify-content-center align-items-center" style="min-height: 100vh;">
  <div class="col-md-4">
    <div class="card mb-4">
      <%= image_tag @user.image, alt: @user.name, class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title"><%= @user.name %></h5>
        <p class="card-text"><strong>Bio:</strong> <%= @user.bio %></p>
        <p class="card-text"><strong>Email:</strong> <%= @user.email %></p>
        <p class="card-text"><strong>Gender:</strong> <%= @gender_name %></p>
        <p class="card-text"><strong>Country:</strong> <%= @country_name %></p>
        <p class="card-text"><strong>Titles:</strong>
          <% if @user.titles.present? %>
            <%= @user.titles.map(&:name).join(', ') %>
          <% else %>
            No titles available
          <% end %>
        </p>
        <p class="card-text"><strong>Created At:</strong> <%= @user.created_at %></p>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h2>Titles:</h2>
<ul>
  <% if @user.titles.present? %>
    <% @user.titles.each do |title| %>
      <li><%= link_to title.name, title_path(title) %></li>
    <% end %>
  <% else %>
    <li>No titles available</li>
  <% end %>
</ul>